### PR TITLE
Fixed documentation in batching

### PR DESCRIPTION
**Pull request by eriophora**
The old PR was #63, but since I pushed from multiple computers apparently this screwed up the CLA. I also had to square the commits down into one. 

This PR clarifies the documentation related to some of the parameters in the batch schedulers. 

Sorry about the spam. I had to do some do some commit-amends to get googlebot to accept the CLA.

### CODE REVIEW

**Comment by chrisolston** [comment]
This PR looks good to me.

**Comment by chrisolston** [comment]
Please squash into a single commit, and then we can accept the PR.

**Comment by eriophora** [comment]
I'm on it!

**Comment by eriophora** [comment]
Tried to follow some directions online, but it refused to squash the commits because of some incomprehensible message having to do with a submodule problem. Asked a colleague to attempt to help but it appears this has only made it worse. So I'm gonna just gonna close the pull request at this time.

**Pull request closed without merging**
