### PR TITLE
Assign Clayne Robison as maintainer for MKL Dockerfiles

### PR DESCRIPTION
**Pull request by ashahba**
Assign the right owner for MKL Dockerfiles.

### CODE REVIEW

**Comment by ashahba** [comment]
@christisg please review.

Thanks.

**Comment by ashahba** [comment]
@mihaimaruseac would you mind review and merging this for me please?

Thanks.

**Comment by mihaimaruseac** [comment]
We cannot accept this on `r2.2` branch as we already released the final release. This should be done on master

**Comment by ashahba** [comment]
@mihaimaruseac no problem. The one against `master` is here: #1605 
Let me close this one then.

**Pull request closed without merging**
