### PR TITLE
Update tensorflow

### PR DESCRIPTION
**Pull request by vladmos**
The currently used version of Tensorflow contains an outdated version of protobuf which is not compatible with the upcoming Bazel 0.8.

### CODE REVIEW

**Comment by kirilg** [comment]
Thanks for the PR! TF@head is not currently compatible with TF Serving, there's a known test failure that we're working to resolve and will update the submodule when it's fixed.

**Comment by vladmos** [comment]
Do you have any estimations when the test will be fixed approximately? Do I need to keep this pull request or should I abandon it and you'll update the submodule yourself?

**Comment by kirilg** [comment]
+ @case540 I don't have an estimate, but yes I think we'll want to update the submodule along with the fix the next time we push (the fix might be in TF so we'll need to sync past what's in this PR).

**Comment by vladmos** [comment]
Is there a Github issue I can track?

**Comment by kirilg** [comment]
The issue has been resolved and we synced to a newer TF.

**Pull request closed without merging**
