### PR TITLE
Add a mnist cpp client

### PR DESCRIPTION
**Pull request by hzy001**
Signed-off-by: hzy001 <haoziyu001@gmail.com>

### CODE REVIEW

**Comment by hzy001** [comment]
signed

**Comment by hzy001** [comment]
updated

**Comment by hzy001** [comment]
updated

**Comment by gautamvasudevan** [comment]
The email address of the change was haoziyu001@gmail.com
I'm guessing that doesn't match the signed CLA

**Comment by hzy001** [comment]
Update the signed CLA

**Comment by hzy001** [comment]
reupdated

**Comment by chrisolston** [comment]
Hi there,

This PR is appreciated, in that we are looking to have more concrete code examples of how to use TF-Serving, including on the client side. We plan to add examples outside of the repository and accompanied by blog posts to really explain how they work -- please stay tuned for those.

Chris

**Pull request closed without merging**
