### PR TITLE
[INTEL MKL] - Fix TF Serving build for oneDNN

### PR DESCRIPTION
**Pull request by ashahba**
- This PR fixes build failure for TFS with oneDNN
- It also switches the bases to `ubuntu:20.04`

### CODE REVIEW

**Comment by ashahba** [comment]
Between now and when the PR is merged, please use these instructions to build the containers:
```
pushd ./serving/tensorflow_serving/tools/docker
TF_SERVING_VERSION_GIT_BRANCH=${TF_SERVING_VERSION_GIT_BRANCH:-master}
TF_SERVING_VERSION_GIT_BRANCH=2.9.1
TF_SERVING_VERSION_GIT_COMMIT=${TF_SERVING_VERSION_GIT_COMMIT:-HEAD}
TF_SERVING_VERSION_GIT_COMMIT=2.9.1
BAZEL_VERSION=${BAZEL_VERSION:-5.1.1}
TF_SERVING_VERSION=${TF_SERVING_VERSION:-$(git rev-parse --short HEAD)}
TF_SERVING_VERSION=2.9.1
TF_SERVING_BUILD_IMAGE="intel-optimized-tensorflow-serving${AVX512}:${TF_SERVING_VERSION}"

docker build \
    ${DOCKER_BUILD_ARGS} \
    -f Dockerfile.devel-mkl \
    --build-arg TF_SERVING_VERSION=${TF_SERVING_VERSION} \
    --build-arg TF_SERVING_BUILD_OPTIONS='--config=mkl --config=release --define=build_with_openmp=false --copt=-march=native' \
    --build-arg TF_SERVING_BAZEL_OPTIONS='--local_ram_resources=HOST_RAM*0.8 --local_cpu_resources=HOST_CPUS-4' \
    --build-arg TF_SERVING_VERSION_GIT_BRANCH=${TF_SERVING_VERSION_GIT_BRANCH} \
    --build-arg BAZEL_VERSION=${BAZEL_VERSION} \
    -t intel/${TF_SERVING_BUILD_IMAGE}-devel-mkl \
    .

docker build \
  ${DOCKER_BUILD_ARGS} \
  --build-arg TF_SERVING_VERSION=${TF_SERVING_VERSION_GIT_BRANCH} \
  --build-arg TF_SERVING_BUILD_IMAGE=intel/intel-optimized-tensorflow-serving:${TF_SERVING_VERSION_GIT_BRANCH}-devel-mkl \
  --build-arg TF_SERVING_VERSION_GIT_BRANCH=${TF_SERVING_VERSION_GIT_BRANCH} \
  --build-arg TF_SERVING_VERSION_GIT_COMMIT=${TF_SERVING_VERSION_GIT_COMMIT} \
  -t intel/intel-optimized-tensorflow-serving:${TF_SERVING_VERSION_GIT_BRANCH}-mkl \
  -f Dockerfile.mkl \
  .
popd
```

and to build `avx512` images:
```
pushd ./serving/tensorflow_serving/tools/docker
export AVX512=avx512
docker build \
  ${DOCKER_BUILD_ARGS} \
  --build-arg TF_SERVING_VERSION=${TF_SERVING_VERSION} \
  --build-arg TF_SERVING_BUILD_IMAGE="intel/intel-optimized-tensorflow-serving:${TF_SERVING_VERSION}-devel-mkl" \
  --build-arg TF_SERVING_BUILD_OPTIONS='--config=mkl --config=release --define=build_with_openmp=false --copt=-march=skylake-avx512' \
  --build-arg TF_SERVING_BAZEL_OPTIONS='--local_ram_resources=HOST_RAM*0.8 --local_cpu_resources=HOST_CPUS-4' \
  --build-arg TF_SERVING_VERSION_GIT_BRANCH=${TF_SERVING_VERSION_GIT_BRANCH} \
  --build-arg TF_SERVING_VERSION_GIT_COMMIT=${TF_SERVING_VERSION_GIT_COMMIT} \
  --build-arg BAZEL_VERSION=5.1.1 \
  -t intel/intel-optimized-tensorflow-serving-${AVX512}:${TF_SERVING_VERSION_GIT_BRANCH}-devel-mkl \
  -f Dockerfile.devel-mkl \
  .

docker build \
  ${DOCKER_BUILD_ARGS} \
  --build-arg TF_SERVING_VERSION=${TF_SERVING_VERSION_GIT_BRANCH} \
  --build-arg TF_SERVING_BUILD_IMAGE=intel/intel-optimized-tensorflow-serving:${TF_SERVING_VERSION_GIT_BRANCH}-devel-mkl-${AVX512} \
  --build-arg TF_SERVING_VERSION_GIT_BRANCH=${TF_SERVING_VERSION_GIT_BRANCH} \
  --build-arg TF_SERVING_VERSION_GIT_COMMIT=${TF_SERVING_VERSION_GIT_COMMIT} \
  -t intel/intel-optimized-tensorflow-serving-${AVX512}:${TF_SERVING_VERSION_GIT_BRANCH}-mkl \
  -f Dockerfile.mkl \
  .
popd
```

Once done, you have the following images ready to use:
```
intel/intel-optimized-tensorflow-serving:2.9.1-devel-mkl
intel/intel-optimized-tensorflow-serving:2.9.1-mkl
intel/intel-optimized-tensorflow-serving-avx512:2.9.1-devel-mkl
intel/intel-optimized-tensorflow-serving-avx512:2.9.1-mkl
```

**Comment by ashahba** [comment]
@rtg0795 would you please review this PR?
Thanks.

**Review by netfs — APPROVED** [review]

**Comment by rtg0795** [comment]
Thanks @netfs .

**Comment by ashahba** [comment]
Thanks @netfs 
However I still don't have merge powers, so feel free to merge on my behalf.

Thanks.

**Pull request merged**
