### PR TITLE
Update bazel version to 0.11.1

### PR DESCRIPTION
**Pull request by eduohe**
Fix for the issue https://github.com/tensorflow/serving/issues/755 serving/tensorflow does not exist

### CODE REVIEW

**Comment by promiseofcake** [comment]
Perhaps we should also bump the min-version for the repo? 
https://github.com/tensorflow/serving/blob/ebde109f39236a124642326a144c364f97fe4d0a/WORKSPACE#L38

**Comment by eduohe** [comment]
Thanks @promiseofcake. Done.

**Comment by eduohe** [comment]
Hi @chrisolston, is there a chance for this PR be merged?

**Comment by gautamvasudevan** [comment]
We've updated to an even newer version of Bazel. Thanks though!

**Comment by eduohe** [comment]
No problem @gautamvasudevan, thanks for the update!

**Pull request closed without merging**
