### PR TITLE
Fix U_FILE_ACCESS_ERROR in tensorflow-text

### PR DESCRIPTION
**Pull request by tgsmith61591**
Addresses #1613 by reworking the `third_party/icu` build chain to more closely resemble the `tf_text/third_party/icu`. I am able to load and serve a model with the `BertTokenizer` without any problems.

### CODE REVIEW

**Comment by tgsmith61591** [comment]
@googlebot I signed it!

**Comment by tgsmith61591** [comment]
It's been a week, can someone acknowledge this, please?

**Comment by elmadj** [comment]
Is there a target date for the Pull Request Review? We need to know the time frame internally so we can adjust/find other solutions.

**Comment by misterpeddy** [comment]
Note, the person who originally wrote this integration is on leave and will likely be able to look at it the week after next at the earliest.

**Comment by broken** [comment]
Hi @tgsmith61591
Apologies for the delay, today is my first day back and I'll take a look at this.

**Comment by broken** [comment]
With TF Serving, they should be building all of the ICU data in, so there shouldn't be a need for patching. The reason for this is that TF & TF Text both have different patched versions of ICU, which works when they are separate libraries. However, TF Serving builds everything together in a single binary, so rather than having to maintain a patch file that combines the two, they've decided to build all the ICU data in (for hope to prevent issues like this).

I suspect if you copy the http_archive currently defined in tensorflow_serving/workspace.bzl to where you have it in WORKSPACE, this should fix the issue. The rest of the changes should not be necessary. I haven't tested this yet, but my reasoning is that I believe TF Serving 2.2.0-rc# is now relying on the TF version of ICU instead of its own which is probably due to an update in the version of Bazel packaged with the Docker build image.

**Comment by tgsmith61591** [comment]
Thanks, @broken, I'll try that out

**Comment by broken** [comment]
This looks good to me. Were you able to test?

**Comment by tgsmith61591** [comment]
I rebuilt yesterday with these changes and ran into the same `U_FILE_ACCESS_ERROR` issue. Doesn't appear the CI checks are public, either

**Comment by broken** [comment]
Ok; I'll build today and look closer at the artifacts.

**Comment by tgsmith61591** [comment]
Thanks @broken

**Comment by broken** [comment]
Okay, I found a few things.

First, the Bazel build for ICU does appear to not be including all the data. I've been having trouble figuring out the right changes needed, so I've reached out to the ICU engineers for help.

Second, it looks like the reason this wasn't caught in TF Serving's tests was that errors in inputs to tf.control_dependencies are silently swallowed when in graph mode. This is a bug in core TF that I've notified them about.

Finally, the sha256 of the ICU zip from GitHub appears to have changed. It's an easy fix, but I find it odd.

**Comment by broken** [comment]
I worked with ICU at trying to bring the bazel build up to date to include all the ICU files. The number of changes is actually quite lengthy, and still requires patching build files in the correct places of the repo bazel checks out to get right. So I'm going to push for having a single patch that includes both TF & TF Text's patches.

I've also found a work around that fixes the regression model to catch this in testing.

And for the last point, it appears like github (today?) rolled back whatever changes it had done to the library that caused the sha to update.

@tgsmith61591 Since the changes should be done in parts, I'm just going to go ahead and send the changes myself to tf serving to make it easier and close the feedback loop. I have discussed with them, and this is a blocker for 2.2.0, so my changes will be included in the next release.

**Comment by broken** [comment]
These changes to the build/workspace and test are in. I expect them to be in the next nightly release. I'll update the corresponding issues.

As a side note, turns out the icu release archive change was due to github previously not including some of the data binaries that were in the repo. We're switching to a Google hosted mirror to prevent this in the future.

**Comment by netfs** [comment]
@broken do we still need this PR? i guess we can close it?

**Comment by broken** [comment]
Yes. This can be closed.

**Pull request closed without merging**
