### PR TITLE
[INTEL MKL] Update maintainer and other MKL dockerfiles improvements

### PR DESCRIPTION
**Pull request by ashahba**
@claynerobison agreed to be the new owner for MKL docker files,

### CODE REVIEW

**Comment by ashahba** [comment]
@christisg please review and let me know if you have any questions.

Thanks.

**Comment by ashahba** [comment]
@mihaimaruseac would you mind review and merging this for me please?

Thanks.

**Comment by mihaimaruseac** [comment]
This will need review from someone from the serving team

**Comment by ashahba** [comment]
@misterpeddy and @mihaimaruseac 
This needs re-review and approve again now that I synced with master and ended up resolving conflicts.

**Comment by ashahba** [comment]
@misterpeddy any feedback on this?

**Comment by ashahba** [comment]
@mihaimaruseac can anyone else approve this?

**Comment by ashahba** [comment]
Thanks @misterpeddy can we get this merged?

**Comment by ashahba** [comment]
Looks like this is already merged as part of this fix: https://github.com/tensorflow/serving/commit/1c4e658ee099ba9b3c53e03f6fecf1277deed37d

**Pull request closed without merging**
