### PR TITLE
Updated Dockerfile, some cleanup, remove redundant stuff

### PR DESCRIPTION
**Pull request by mahnunchik**
Dockerfile:
* updated ubuntu to 16.04
* removed unnecessary ppa of JDK8
* updated bazel to 0.5.1
* removed unnecessary hacks for bazel
* updated python modules

### CODE REVIEW

**Comment by mahnunchik** [comment]
I signed it!

**Comment by chrisolston** [comment]
Looks good except for one question: Did you intend to remove the protobuf dependency? (Perhaps it comes transitively now?)

**Comment by mahnunchik** [comment]
Hi @chrisolston 

Yes I removed `six`, `protobuf`, `futures`, and `enum34` modules because `grpcio` depends on it. According https://pypi.python.org/pypi/grpcio/1.3.5
As a result, the installed dependencies are the same.

**Comment by mahnunchik** [comment]
[`Dockerfile.devel-gpu`](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel-gpu) could be updated almost the same way, but I don't have CUDA card to verify my changes.

**Pull request merged**
