### PR TITLE
Enable BFloat16 Automatic Mixed Precision (AMP) in TensorFlow Serving

### PR DESCRIPTION
**Pull request by nhatleSummer22**
This PR allows users to enable BFloat16 AMP by adding `--mixed_precision=bfloat16` flag when starting the model server.

AMP can accelerate inference significantly. We observed different degrees of speedup for TensorFlow Hub detection models. For example: [faster_rcnn/inception_resnet_v2_1024x1024 ](https://tfhub.dev/tensorflow/faster_rcnn/inception_resnet_v2_1024x1024/1)can achieve ~1.4X speedup when BFloat16 AMP is enabled, compared to running inference with the FP32 model.

### CODE REVIEW

**Comment by agramesh1** [comment]
CC @penpornk @cantonios

**Review by xiaoxlu — APPROVED** [review]

**Comment by nhatleSummer22** [comment]
@xiaoxlu Thank you for approving the PR. Please let me know if anything else needed from my side to get it merged. Thanks!

**Comment by nhatleSummer22** [comment]
@xiaoxlu Thanks for looking into this. Could you please let me know what is failing? I could not access the build status details.

**Comment by nhatleSummer22** [comment]
@xiaoxlu Somehow I still cannot see the build failed details. Could you please take a look? Thanks!

**Pull request merged**
