### PR TITLE
Update TF Text to v2.4.3.

### PR DESCRIPTION
**Pull request by supercharleszhu**
Update TF Text to v2.4.3. Picking up changes from https://github.com/tensorflow/serving/commit/ccfb606b2c86f4ffb57ecd8454c8809ab8c13090#diff-bd436285f77efec760a31396a2280da70086b990f946fc7759ca58b137c2069f

### CODE REVIEW

**Comment by supercharleszhu** [comment]
@googlebot I signed it!

**Review by asamadiya — APPROVED** [review]

**Review by broken — APPROVED** [review]
Thanks!

**Comment by asamadiya** [comment]
@netfs @broken Can this be merged?

**Comment by broken** [comment]
Apologies; I didn't realize I had the necessary permissions to submit the merge.

**Pull request merged**
