### PR TITLE
List all model names

### PR DESCRIPTION
**Pull request by yupbank**
Add a grpc service to list all the model names available.

addressing https://github.com/tensorflow/serving/issues/795

### CODE REVIEW

**Comment by yupbank** [comment]
@case540 @kirilg is there a reason we pre-generate `model_service_pb2.py` and `model_service_pb2_grpc.py` ?

**Comment by case540** [comment]
Not sure

**Comment by yupbank** [comment]
why it's closed?

**Comment by chrisolston** [comment]
The TF-Serving team would like to suggest an alternative approach. Please see the discussion in https://github.com/tensorflow/serving/pull/809

**Pull request closed without merging**
